### ISSUE TITLE
sticky-session: worker died error TypeError: Cannot call method 'removeListener' of undefined

### ISSUE THREAD

**Issue by Alexandrrr** [indutny/sticky-session#22]
Hello.
I had a problem with my project. If I hold down the button F5 to reload my page, which is rendered by GET request, nodeserver is down with exception:
sticky-session: worker died
error TypeError: Cannot call method 'removeListener' of undefined

CallStack:
at httpSocketSetup (http.js:1859:10)
    at Server.connectionListener (http.js:1928:3)
    at Server.emit (events.js:95:17)
    at process.<anonymous> (/var/www/producer/data/www/producer.lifeha.ru/project/node_modules/sticky-session/lib/sticky-session.js:63:14)
    at process.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
sticky-session: worker died

**Comment by liebo** [comment]
the same problem when high concurrent connection number

**Comment by triitvn** [comment]
@liebo @Alexandrrr I have the same issue. I use sitcky session with socket.io. How can we setup a high-traffic websocket server?

**Comment by Mad-Head** [comment]
<b>Cause of error: </b>
You tried to "server.emit ('connection', socket);" in sticky-session.js: 63 line, where: variable "socket" is undefined.

<b>Solution:</b> add a validation variable.

<b>For example:</b>
```javascript
    process.on('message', function(msg, socket) {
      if (msg !== 'sticky-session:connection') return;
      if (socket) {
        server.emit('connection', socket);
      } else {
        console.log('Warning: socket is not defined');
      }
    });
```

**Comment by triitvn** [comment]
Thank you @Mad-Head so much.
