### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by zlokomatic** [indutny/sticky-session#40]
Hi,

after some time and > 10000 connections i am seeing many errors with:

Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

After that no new connections are accepted.

I found a nodejs issue 
https://github.com/nodejs/node-v0.x-archive/issues/7566 but i am not sure this is the problem and i dont know how to fix this maybe you can help?

**Comment by zlokomatic** [comment]
The problem was caused by a wrong haproxy configuration.
Actually we just needed mode http and keep-alive enabled
