### ISSUE TITLE
Doesn't work with socket.io

### ISSUE THREAD

**Issue by kselax** [indutny/sticky-session#59]
I created code cluster.js
`// cluster.js
const cluster = require('cluster');
const os = require('os');

var sticky = require('sticky-session');

var server = require('http').createServer(function(req, res) {
  // res.end('worker: ' + cluster.worker.id);
  require('./index.js');
});

if (!sticky.listen(server, 3000)) {
  // Master code
  // if (cluster.isMaster) {
  //   const cpus = os.cpus().length;
  //
  //   console.log(`Forking for ${cpus} CPUs`);
  //   for (let i = 0; i<cpus; i++) {
  //     cluster.fork();
  //   }
  // }

  server.once('listening', function() {
    console.log('server started on 3001 port');
  });
  //
} else {
  // Worker code
  require('./index.js');
}

// if (cluster.isMaster) {
//   const cpus = os.cpus().length;
//
//   console.log(`Forking for ${cpus} CPUs`);
//   for (let i = 0; i<cpus; i++) {
//     cluster.fork();
//   }
// } else {
//   require('./index.js');
// }
`
file index.js
`var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

io.on('connection', function(socket){
  console.log('a user connected');
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});
`
and index.html
`<!doctype html>
<html>
  <head>
    <title>Socket.IO chat</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font: 13px Helvetica, Arial; }
      form { background: #000; padding: 3px; position: fixed; bottom: 0; width: 100%; }
      form input { border: 0; padding: 10px; width: 90%; margin-right: .5%; }
      form button { width: 9%; background: rgb(130, 224, 255); border: none; padding: 10px; }
      #messages { list-style-type: none; margin: 0; padding: 0; }
      #messages li { padding: 5px 10px; }
      #messages li:nth-child(odd) { background: #eee; }
    </style>
  </head>
  <body>
    <ul id="messages"></ul>
    <form action="">
      <input id="m" autocomplete="off" /><button>Send</button>
    </form>
  </body>
</html>
`

and got an error
`...
Error: bind EADDRINUSE null:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at listenOnMasterHandle (net.js:1415:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)

    at _combinedTickCallback (internal/process/next_tick.js:141:11)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: bind EADDRINUSE null:3000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at listenOnMasterHandle (net.js:1415:16)
    at rr (internal/cluster/child.js:121:12)
    at Worker.send (internal/cluster/child.js:88:7)
    at process.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)`

**Comment by SSSensation** [comment]
I am facing about this problems too, Is this package still working? or Can anyone give some example code in details plz.
